config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    post :actions, controller: 'slack'
    get :invalid_token, controller: 'slack'
    post :events, controller: 'slack'
    post :interactive, controller: 'slack'
    
    resources :people, only: [] do
      collection do
        post :status
        post :register
        post :away
        post :here
      end
    end
  end

  resources :people
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
end

app/models/person.rb
require 'action_view'
require 'action_view/helpers'

class Person < ApplicationRecord
  include ActionView::Helpers::DateHelper
  belongs_to :product, optional: true
  has_many :tickets

  validates :slack_id, uniqueness: { message: "id already registered" }

  def status(all = false)
    if available?
      "#{slack_handle} is *available* and working on *#{working_on}* tickets"
    elsif all
      "#{slack_handle} was marked *away* #{time_ago_in_words(self.updated_at)} ago"
    end
  end

  def user_mention
    "<@#{slack_id}>"
  end

  def working_on
    reload
    self.product.nil? ? "any" : self.product.name
  end

  def set_away
    self.update_attribute(:available, false)
  end

  def update_email(email = nil)
    self.update_attribute(:slack_email, email)
  end

  def set_here(product = nil)
    Rails.logger.info product.inspect
    self.product = product
    self.available = true

    self.save
  end
end

app/controllers/api/people_controller.rb
class Api::PeopleController < ApplicationApiController
  before_action :find_person, only: [:away, :here]

  # POST /people/register
  # Used for register new user from slack /support-register command
  def register
    logger.info params.inspect
    message = MySlack::People.register(params[:user_id])

    render json: message
  end

  def status
    render json: MySlack::People.list
  end

  def here
    unless params[:text].blank?

    end

    render json: MySlack::People.set_here(params[:user_id], params[:text])
  end

  def away
    render json: MySlack::People.set_away(params[:user_id])
  end

  def update_email
    render json: MySlack::People.update_email(params[:user_id],params[:text])
  end

  private
    def register_slack_params
      {
        slack_id: params[:user_id],
        slack_email: params[:user_email],
        slack_handle: params[:user_name],
        available: true
      }
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :slack_id, :slack_handle, :slack_email, :available, :product_id)
    end
end

app/helpers/api/people_helper.rb
module Api::PeopleHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.haml
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :slack_id
    = f.text_field :slack_id
  .field
    = f.label :slack_email
    = f.text_field :slack_email
  .field
    = f.label :slack_handle
    = f.text_field :slack_handle
  .field
    = f.label :available
    = f.check_box :available
  .field
    = f.label :product
    = f.text_field :product
  .actions
    = f.submit 'Save'

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people

%table
  %thead
    %tr
      %th Name
      %th Slack
      %th Email
      %th Slack handle
      %th Available
      %th Product
      %th
      %th
      %th

  %tbody
    - @people.each do |person|
      %tr
        %td= person.name
        %td= person.slack_id
        %td= person.slack_email
        %td= person.slack_handle
        %td= person.available
        %td= person.product
        %td= link_to 'Show', person
        %td= link_to 'Edit', edit_person_path(person)
        %td= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Person', new_person_path

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @person.name
%p
  %b Slack:
  = @person.slack_id
%p
  %b Email:
  = @person.slack_email
%p
  %b Slack handle:
  = @person.slack_handle
%p
  %b Available:
  = @person.available
%p
  %b Product:
  = @person.product

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'Back', people_path